/**
 * Types-only exports from wn-ts-core
 * 
 * This file exports only the types and interfaces needed by consumers
 * without including test utilities or other heavy dependencies.
 */

// Core types
export type {
  Word,
  Sense,
  Synset,
  Lexicon,
  Definition,
  Example,
  Relation,
  Form,
  Pronunciation,
  Tag,
  Count,
  ILI,
  Statistics,
  PartOfSpeech,
  Language,
  QueryOptions,
  WordQuery,
  SenseQuery,
  SynsetQuery,
  LexiconQuery,
  StatisticsQuery,
  QueryResult,
  QueryError,
  QueryService,
  Database,
  DatabaseConnection,
  DatabaseTransaction,
  DatabaseQuery,
  DatabaseResult,
  DatabaseError,
  DatabaseConfig,
  DatabaseOptions,
  DatabaseSchema,
  DatabaseTable,
  DatabaseColumn,
  DatabaseIndex,
  DatabaseConstraint,
  DatabaseForeignKey,
  DatabaseTrigger,
  DatabaseView,
  DatabaseFunction,
  DatabaseProcedure,
  DatabaseSequence,
  DatabaseType,
  DatabaseValue,
  DatabaseRow,
  DatabaseRows,
  DatabaseField,
  DatabaseFields,
  DatabaseRecord,
  DatabaseRecords,
  DatabaseCursor,
  DatabaseStatement,
  DatabasePreparedStatement,
  DatabaseBlob,
  DatabaseClob,
  DatabaseArray,
  DatabaseObject,
  DatabaseJSON,
  DatabaseXML,
  DatabaseBinary,
  DatabaseText,
  DatabaseNumeric,
  DatabaseInteger,
  DatabaseReal,
  DatabaseBoolean,
  DatabaseDate,
  DatabaseTime,
  DatabaseTimestamp,
  DatabaseInterval,
  DatabaseUUID,
  DatabaseGUID,
  DatabaseHash,
  DatabaseChecksum,
  DatabaseSignature,
  DatabaseCertificate,
  DatabaseKey,
  DatabaseSecret,
  DatabaseToken,
  DatabaseSession,
  DatabaseUser,
  DatabaseRole,
  DatabasePermission,
  DatabaseGrant,
  DatabaseRevoke,
  DatabasePrivilege,
  DatabaseAccess,
  DatabaseSecurity,
  DatabaseAudit,
  DatabaseLog,
  DatabaseTrace,
  DatabaseDebug,
  DatabaseProfile,
  DatabaseMonitor,
  DatabaseMetrics,
  DatabaseStats,
  DatabasePerformance,
  DatabaseOptimization,
  DatabaseTuning,
  DatabaseMaintenance,
  DatabaseBackup,
  DatabaseRestore,
  DatabaseRecovery,
  DatabaseMigration,
  DatabaseUpgrade,
  DatabaseDowngrade,
  DatabaseVersion,
  DatabaseRelease,
  DatabaseBuild,
  DatabaseDeployment,
  DatabaseEnvironment,
  DatabaseConfiguration,
  DatabaseSettings,
  DatabasePreferences,
  DatabaseOptions as DatabaseOptionsType,
  DatabaseConfig as DatabaseConfigType,
  DatabaseSchema as DatabaseSchemaType,
  DatabaseTable as DatabaseTableType,
  DatabaseColumn as DatabaseColumnType,
  DatabaseIndex as DatabaseIndexType,
  DatabaseConstraint as DatabaseConstraintType,
  DatabaseForeignKey as DatabaseForeignKeyType,
  DatabaseTrigger as DatabaseTriggerType,
  DatabaseView as DatabaseViewType,
  DatabaseFunction as DatabaseFunctionType,
  DatabaseProcedure as DatabaseProcedureType,
  DatabaseSequence as DatabaseSequenceType,
  DatabaseType as DatabaseTypeType,
  DatabaseValue as DatabaseValueType,
  DatabaseRow as DatabaseRowType,
  DatabaseRows as DatabaseRowsType,
  DatabaseField as DatabaseFieldType,
  DatabaseFields as DatabaseFieldsType,
  DatabaseRecord as DatabaseRecordType,
  DatabaseRecords as DatabaseRecordsType,
  DatabaseCursor as DatabaseCursorType,
  DatabaseStatement as DatabaseStatementType,
  DatabasePreparedStatement as DatabasePreparedStatementType,
  DatabaseBlob as DatabaseBlobType,
  DatabaseClob as DatabaseClobType,
  DatabaseArray as DatabaseArrayType,
  DatabaseObject as DatabaseObjectType,
  DatabaseJSON as DatabaseJSONType,
  DatabaseXML as DatabaseXMLType,
  DatabaseBinary as DatabaseBinaryType,
  DatabaseText as DatabaseTextType,
  DatabaseNumeric as DatabaseNumericType,
  DatabaseInteger as DatabaseIntegerType,
  DatabaseReal as DatabaseRealType,
  DatabaseBoolean as DatabaseBooleanType,
  DatabaseDate as DatabaseDateType,
  DatabaseTime as DatabaseTimeType,
  DatabaseTimestamp as DatabaseTimestampType,
  DatabaseInterval as DatabaseIntervalType,
  DatabaseUUID as DatabaseUUIDType,
  DatabaseGUID as DatabaseGUIDType,
  DatabaseHash as DatabaseHashType,
  DatabaseChecksum as DatabaseChecksumType,
  DatabaseSignature as DatabaseSignatureType,
  DatabaseCertificate as DatabaseCertificateType,
  DatabaseKey as DatabaseKeyType,
  DatabaseSecret as DatabaseSecretType,
  DatabaseToken as DatabaseTokenType,
  DatabaseSession as DatabaseSessionType,
  DatabaseUser as DatabaseUserType,
  DatabaseRole as DatabaseRoleType,
  DatabasePermission as DatabasePermissionType,
  DatabaseGrant as DatabaseGrantType,
  DatabaseRevoke as DatabaseRevokeType,
  DatabasePrivilege as DatabasePrivilegeType,
  DatabaseAccess as DatabaseAccessType,
  DatabaseSecurity as DatabaseSecurityType,
  DatabaseAudit as DatabaseAuditType,
  DatabaseLog as DatabaseLogType,
  DatabaseTrace as DatabaseTraceType,
  DatabaseDebug as DatabaseDebugType,
  DatabaseProfile as DatabaseProfileType,
  DatabaseMonitor as DatabaseMonitorType,
  DatabaseMetrics as DatabaseMetricsType,
  DatabaseStats as DatabaseStatsType,
  DatabasePerformance as DatabasePerformanceType,
  DatabaseOptimization as DatabaseOptimizationType,
  DatabaseTuning as DatabaseTuningType,
  DatabaseMaintenance as DatabaseMaintenanceType,
  DatabaseBackup as DatabaseBackupType,
  DatabaseRestore as DatabaseRestoreType,
  DatabaseRecovery as DatabaseRecoveryType,
  DatabaseMigration as DatabaseMigrationType,
  DatabaseUpgrade as DatabaseUpgradeType,
  DatabaseDowngrade as DatabaseDowngradeType,
  DatabaseVersion as DatabaseVersionType,
  DatabaseRelease as DatabaseReleaseType,
  DatabaseBuild as DatabaseBuildType,
  DatabaseDeployment as DatabaseDeploymentType,
  DatabaseEnvironment as DatabaseEnvironmentType,
  DatabaseConfiguration as DatabaseConfigurationType,
  DatabaseSettings as DatabaseSettingsType,
  DatabasePreferences as DatabasePreferencesType
} from './types/index.js';

// Query service types
export type {
  QueryService as QueryServiceType,
  WordQuery as WordQueryType,
  SenseQuery as SenseQueryType,
  SynsetQuery as SynsetQueryType,
  LexiconQuery as LexiconQueryType,
  StatisticsQuery as StatisticsQueryType,
  QueryResult as QueryResultType,
  QueryError as QueryErrorType,
  QueryOptions as QueryOptionsType
} from './shared/base-query-service.js';
